name: RFC (org-wide)
description: Propose a cross-repo change for review.
title: "[RFC] <short title>"
labels: [org-wide, rfc, needs-triage]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: Why is this needed? Who benefits?
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: Design/Approach
      placeholder: Architecture, alternatives, rollout plan
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Affected repos/teams
      placeholder: Repos, APIs, contracts
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks and mitigations
  - type: textarea
    id: metrics
    attributes:
      label: Success metrics
